Location feature
neuefische/hh-2020-w4-rickandmorty-team1 pull request #8
Opened 2020-08-18 21:53 UTC by annidrumm

Add location-feature #1 
- solved issue
- copied PageNav from max episodes #7
- still some styling needed

2020-08-18 21:54 UTC, mpagels approved these changes

2020-08-19 06:18 UTC, maxbischof commented
This pull request brings in a second version of cards styling. Lets discuss a general version. This shouldn't be a blocker for this pull request. Therefore I created an issue [here](https://github.com/neuefische/hh-2020-w4-rickandmorty-team1/issues/11).

2020-08-19 06:32 UTC, maxbischof requested changes
Thanks for the location feature. I added some feedback.

2020-08-19 06:32 UTC, maxbischof commented on src/components/pages/Locations/Location.js
> +export default function Location({ name, type, dimension, residents }) {
Should we name the components Location and Episode? Or LocationCard and EpisodeCard? Right now we have mixed naming.

2020-08-19 06:32 UTC, maxbischof commented on src/components/pages/Locations/LocationPage.js
> +      })
```suggestion
    fetchPageData(1)
```

2020-08-19 06:32 UTC, maxbischof commented on src/components/pages/Locations/LocationPage.js
> +      })
```suggestion
    fetch('https://rickandmortyapi.com/api/location/?page=' + page)
      .then((res) => res.json())
      .then((data) => {
        setlocation(data.results)
        setPages(data.info.pages)
      })
```

2020-08-19 06:32 UTC, maxbischof commented on src/components/pages/Locations/LocationPage.js
> +      ))}
I am always asking myself if its good practice to have logic in the return statement. What do you think? @annidrumm  @mpagels  @annaleaschroeder

2020-08-19 07:23 UTC, annidrumm commented on src/components/pages/Locations/Location.js
> +export default function Location({ name, type, dimension, residents }) {
Thanks for your feedback. And Good point. I prefer LocationCard as well and will update it today.

2020-08-19 07:34 UTC, mpagels commented on src/components/pages/Locations/Location.js
> +export default function Location({ name, type, dimension, residents }) {
LocationCard is way better for the understanding.

2020-08-19 10:18 UTC, annidrumm commented
New issue:

- make it mobile friendly

2020-08-19 12:05 UTC, merged